language: java
before_install: cd plugin-logic
after_success:
  - mvn clean cobertura:cobertura coveralls:cobertura
notifications:
  irc:
    channels:
      - "irc.nbl.fi#tmc-eclipse"
    on_success: always # default: always
    on_failure: always # default: always
